tellme/urls.py
import django

try:
    from django.urls import path, include
except ImportError:
    from django.conf.urls import url, include


from .views import get_feedback_screenshot, post_feedback


if django.VERSION[0] < 2:
    tellme_urlpatterns = [
        url(r'^post_feedback/$', post_feedback, name='post_feedback'),
        url(r'^get_feedback_screenshot/(?P<pk>\d+)/$', get_feedback_screenshot, name='get_feedback_screenshot'),
    ]

    urlpatterns = [
        url(r'^', include(tellme_urlpatterns,
            namespace='tellme')),
    ]
else:
    tellme_urlpatterns = [
        path('post_feedback/', post_feedback, name='post_feedback'),
        path('get_feedback_screenshot/<int:pk>/', get_feedback_screenshot, name='get_feedback_screenshot'),
    ]

    app_name = 'tellme'

    urlpatterns = [
        path('', include(tellme_urlpatterns,)),
    ]

tellme/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import post_delete
from django.dispatch.dispatcher import receiver
from django.utils.translation import ugettext_lazy as _
from six import python_2_unicode_compatible

try:
    from django.core.urlresolvers import reverse
except ImportError:
    from django.urls import reverse


@python_2_unicode_compatible
class Feedback(models.Model):
    url = models.CharField(_('Url'), max_length=255)
    browser = models.TextField(_('Browser'))
    comment = models.TextField(_('Comment'))
    screenshot = models.ImageField(_('Screenshot'), blank=True, null=True, upload_to="tellme/screenshots/")

    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_("User"), on_delete=models.SET_NULL, blank=True, null=True)
    email = models.EmailField(max_length=254, blank=True, null=True)
    created = models.DateTimeField(_('Creation date'), auto_now_add=True, db_index=True)

    ack = models.BooleanField(_('Acknowledgement'), default=False)

    class Meta:
        verbose_name = _("feedback")
        verbose_name_plural = _("feedbacks")

    def __str__(self):
        return '%s: %s' % (self.created, self.url)
    
    def get_screenshot_url(self):
        return reverse('tellme:get_feedback_screenshot', kwargs={'pk': self.pk})


@receiver(post_delete, sender=Feedback)
def feedback_screenshot_delete(sender, instance, **kwargs):
    """
    Delete feedback's screenshot.
    """
    if instance.screenshot:
        instance.screenshot.delete(save=False)

tellme/forms.py
from django.forms import ModelForm
from .models import Feedback


class FeedbackForm(ModelForm):

    class Meta:
        model = Feedback
        fields = "__all__"

tellme/views.py
import json
from base64 import b64decode
import importlib

from django.conf import settings
from django.http import JsonResponse, HttpResponseBadRequest
from django.core.files.base import ContentFile
from django.shortcuts import redirect, get_object_or_404
from django.utils.crypto import get_random_string

from tellme.forms import FeedbackForm
from tellme.models import Feedback
from tellme import mail


def get_notification_function(path=None):
    path = path or getattr(settings, 'TELLME_NOTIFICATION_FUNCTION',
                           'tellme.mail.send_mail')
    module_path = '.'.join(path.split('.')[:-1])
    func_name = path.split('.')[-1]
    module = importlib.import_module(module_path)
    func = getattr(module, func_name)
    return func


def post_feedback(request):
    if request.method == 'POST' and request.is_ajax():

        # Copy Post data names into names used into the model in order to automatically create the model/form
        # from the request dicts
        feedback = json.loads(request.POST["feedback"])
        if request.user.id:
            data = {'url': feedback['url'], 'browser': json.dumps(feedback['browser']), 'comment': feedback['note'],
                        'user': request.user.id}
        else:
            data = {'url': feedback['url'], 'browser': json.dumps(feedback['browser']), 'comment': feedback['note'],
                        'email': feedback.get('email')}
        imgstr = feedback['img'].split(';base64,')[1]
        file = {'screenshot': ContentFile(b64decode(imgstr), name="screenshot_" + get_random_string(6) + ".png")}
        form = FeedbackForm(data, file)
        # check whether it's valid:
        if form.is_valid():
            f = form.save()

            if hasattr(settings, 'TELLME_FEEDBACK_EMAIL'):
                send_notif = get_notification_function()
                send_notif(request, f)
            return JsonResponse({})
        else:
            return JsonResponse({'error': dict(form.errors)})

    else:
        return HttpResponseBadRequest()


def get_feedback_screenshot(request, pk):
    instance = get_object_or_404(Feedback, pk=pk)
    return redirect(instance.screenshot.url)

tellme/templates/tellme/css_inc.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'tellme/vendor/feedback/feedback.css' %}">

tellme/templates/tellme/js_inc.html
{% load static %}

{#Extend with an empty block or replace with your version of jquery#}
{%  block jquery %}
    <script src="{% static 'tellme/vendor/jquery/jquery-3.5.1.js' %}"></script>
{% endblock %}

{% block es6promise %}
    <script src="{% static 'tellme/vendor/es6-promise/es6-promise.auto.js' %}"></script>
{% endblock %}


{# Extend with an empty block if you other mean to deal with AJAX post request in Django #}
{%  block ajax_csrf %}
    <script type="text/javascript">
        // using jQuery
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie != '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) == (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        var csrftoken = getCookie('csrftoken');
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });
    </script>
{% endblock %}

{% block feedback %}
    <script src="{% static 'tellme/vendor/feedback/feedback.js' %}"></script>
{% endblock %}

{#This is the actual code that enables the tellme plugin#}
{% block enable_tellme %}
    <script type="text/javascript">
        $(function () {
            if (!$('#feedback-btn').length) {
                var $btn = $("{% filter escapejs %}{% include 'tellme/tpl-button.html' %}{% endfilter %}");
                $('body').append($btn);
                if (!$('#feedback-btn').length) {
                    $btn.attr('id', 'feedback-btn');
                }
            }
            $.feedback({
                ajaxURL: "{% url 'tellme:post_feedback' %}",
                html2canvasURL: "{% block html2canvasURL %}{% static 'tellme/vendor/html2canvas/html2canvas.js' %}{%  endblock %}",
                feedbackButton: "#feedback-btn",
                initButtonText: "{% filter escapejs %}{%  include 'tellme/initButtonText.txt' %}{% endfilter %}",
                postHTML: false,
                tpl: {
                    description: "{% filter escapejs %}{%  include 'tellme/tpl-description.html' %}{% endfilter %}",
                    highlighter: "{% filter escapejs %}{%  include 'tellme/tpl-highlighter.html' %}{% endfilter %}",
    				overview:	 "{% filter escapejs %}{%  include 'tellme/tpl-overview.html' %}{% endfilter %}",
    				submitSuccess:"{% filter escapejs %}{%  include 'tellme/tpl-submit-success.html' %}{% endfilter %}",
    				submitError: "{% filter escapejs %}{%  include 'tellme/tpl-submit-error.html' %}{% endfilter %}"
                },
                initialBox: true
            });
        });
    </script>
{%  endblock %}

tellme/templates/tellme/tpl-button.html
{% load i18n %}
<button type="button">{% trans 'report an issue on this page' %}</button>

tellme/templates/tellme/tpl-description.html
{% load i18n %}
<div id="feedback-welcome">
    <div class="feedback-logo">{% trans 'Feedback' %}</div>
    <p>{% trans 'Feedback lets you send us suggestions about this site. We welcome problem reports, feature ideas and general comments.' %}</p>
    {% if not user.is_authenticated %}
        <p>{% trans 'If you wish to be contacted please leave us your email:' %}</p>
        <input type='text' name="Email" id="feedback-user-email">
    {% endif %}
    <p>{% trans 'Start by writing a brief description:' %}</p>
    <textarea id="feedback-note-tmp"></textarea>
    <p>{% trans "Next we'll let you identify areas of the page related to your description." %}</p>
    <button id="feedback-welcome-next" class="feedback-next-btn feedback-btn-gray">{% trans 'Next' %}</button>
    <div id="feedback-welcome-error">{% trans 'Please enter a description.' %}</div>
    <div class="feedback-wizard-close"></div>
</div>

tellme/templates/tellme/tpl-highlighter.html
{% load i18n %}
<div id="feedback-highlighter">
    <div class="feedback-logo">{% trans 'Feedback' %}</div>
    <p>{% trans "Click and drag on the page to help us better understand your feedback. You can move this dialog if it's in the way." %}</p>
    <button class="feedback-sethighlight feedback-active">
        <span class="ico"></span>
        <span>{% trans 'Highlight' %}</span></button>
    <label>{% trans 'Highlight areas relevant to your feedback.' %}</label>
    <button class="feedback-setblackout">
        <span class="ico"></span>
        <span>{% trans 'Black out' %}</span></button>
    <label class="lower">{% trans 'Black out any personal information.' %}</label>
    <div class="feedback-buttons">
        <button id="feedback-highlighter-next" class="feedback-next-btn feedback-btn-gray">
            {% trans 'Next' %}
        </button>
        <button id="feedback-highlighter-back" class="feedback-back-btn feedback-btn-gray">
            {% trans 'Back' %}
        </button>
    </div>
    <div class="feedback-wizard-close"></div>
</div>

tellme/templates/tellme/tpl-overview.html
{% load i18n %}
<div id="feedback-overview">
    <div class="feedback-logo">{% trans 'Feedback' %}</div>
    <div id="feedback-overview-description">
        <div id="feedback-overview-description-text"><h3>{% trans 'Description' %}</h3>
            <h3 class="feedback-additional">{% trans 'Additional info' %}</h3>
            <div id="feedback-additional-none"><span>{% trans 'None' %}</span></div>
            <div id="feedback-browser-info"><span>{% trans 'Browser Info' %}</span></div>
            <div id="feedback-page-info"><span>{% trans 'Page Info' %}</span></div>
            <div id="feedback-page-structure"><span>{% trans 'Page Structure' %}</span></div>
        </div>
    </div>
    <div id="feedback-overview-screenshot"><h3>{% trans 'Screenshot' %}</h3></div>
    <div class="feedback-buttons">
        <button id="feedback-submit" class="feedback-submit-btn feedback-btn-blue">{% trans 'Submit' %}</button>
        <button id="feedback-overview-back" class="feedback-back-btn feedback-btn-gray">{% trans 'Back' %}</button>
    </div>
    <div id="feedback-overview-error">{% trans 'Please enter a description.' %}</div>
    <div class="feedback-wizard-close"></div>
</div>

tellme/templates/tellme/tpl-submit-error.html
{% load i18n %}
<div id="feedback-submit-error">
    <div class="feedback-logo">{% trans 'Feedback' %}</div>
    <p>{% trans 'Sadly an error occurred while sending your feedback. Please try again.' %}</p>
    <button class="feedback-close-btn feedback-btn-blue">{% trans 'OK' %}</button>
    <div class="feedback-wizard-close"></div>
</div>

tellme/templates/tellme/tpl-submit-success.html
{% load i18n %}
<div id="feedback-submit-success">
    <div class="feedback-logo">{% trans 'Feedback' %}</div>
    <p>{% trans 'Thank you for your feedback. We value every piece of feedback we receive.'%}</p>
    <p>{% trans 'We cannot respond individually to every one, but we will use your comments as we strive to improve your experience.' %}</p>
    <button class="feedback-close-btn feedback-btn-blue">{% trans 'OK' %}</button>
    <div class="feedback-wizard-close"></div>
</div>